### ISSUE TITLE
Guitar Problems

### ISSUE THREAD

**Issue by TrustierEmu** [TurkeyMan/feedback-editor#2]
Hey so i was having trouble because the original configuration of the buttons on ps3 controllers dont match up with the inputs on programs (Pressing green will press red on program) long story short, is there a way to stop only FeedBack from detecting guitar inputs? if so, let me know. Thanks

**Comment by TurkeyMan** [comment]
Sorry, the first and second sentence don't seem to follow. I'm not sure what you're asking?

**Comment by TrustierEmu** [comment]
So my guitar's buttons are, To say the least, messed up, so if i were to press green on the guitar, my computer thinks that im pressing red, and its all mixed up. So i got JoyToKey to remap the guitars buttons to keyboard keys, but FeedBack is still detecting the old controls, along with the keyboard keys, so i was wondering if there was a way to stop feedback from detecting my guitar's buttons and only detect the keyboard.

**Comment by TurkeyMan** [comment]
Did you edit the controls in `Config.ini`? You can probably just correct the guitar controls directly in there.

**Comment by TurkeyMan** [comment]
The reason your guitar doesn't work, is because that version of the game wasn't invented when I wrote feedback ;)

**Comment by TrustierEmu** [comment]
Alright that seemed to have fixed it. Thanks so much man.

**Comment by TurkeyMan** [comment]
Np
